.\" Manpage for screen-generator
.TH SCREEN-GENERATOR 1 "2016-07-31" "1.0" "screen-generator v0.3.7"
.SH NAME

screen-generator, screeng \- generates screen configuration files and launches screen by providing a chain of commands or a window configuration
.SH SYNOPSIS

.B "screen-generator [-c COMMAND CHAIN] [-x X] [-y Y] [-d DESTINATION PATH] [-n] [-v]"
.SH DESCRIPTION
.B Screen-generator
generates screen configuration files by only providing window commands. screen-generator automatically find the number of windows needed given the command chains.

The number of windows can also be specifed in alone or in conjunction with a command chain. It can for instance generate any screenrc defining a grid of 
.B X
lines and 
.B Y
columns.

Window commands can be chose by using 
.B -c 
flag with a set of commands separated by commas (e.g "bash;watch ls;watch lsblk;tcpdum") or by newlines. 

If no command chain is given, window commands become the default shell $SHELL.
  
The path of the new screen configuration file can be specified using 
.B -d DESTINATION PATH
\.
If the flag 
.B -d
is not set, the location becomes 
.B /tmp/screenrc-XxY

The Nth command in the chain gives the command of the Nth window counting from top lef to bottom right.

The number of windows is automatically guessed depending on the command chain but can also be set using 
.B -x
and 
.B -y
flags.

If no command chain nor screen size is given, default values of 1 and 2 are taken (given by variables 
.B DEFAULT_NUMBER_OF_LINES
and
.B DEFAULT_NUMBER_OF_COLUMNS. 

Screen can be prevented from being lauched by adding the option 
.B -n
\.
The option 
.B -t allow to print the newly generated screen on the terminal.
.SH OPTIONS

.TP
.B -c COMMAND CHAIN
Specify window command from a set of commands COMMAND CHAIN separated by commas (e.g "bash;watch ls;watch lsblk") or by a newlines. 
.TP
.B -x X 
Specify the number of lines. This will overwrite the value guessed if command chain is given.
.TP
.B -y Y
Specify the number of columns. This will overwrite the value guessed if command chain is given.
.TP
.B -d DESTINATION PATH 
Specify the destination of the generated configuration file (
.B /tmp/.screenrc-XxY-ADJUSTED COMMAND CHAIN STRING
if not mentioned )
.TP
.B -m WINDOW NUMBER 
Move the cursor to 
.BR WINDOW
.BR NUMBER .
Windows are numbered from top-left to bottom right, line by lines. The cursor is set to the first added shell if not specifies
.TP
.B -n
Prevent from executing screen. It only generate screen configuration file ( given by DESTINATION PATH or /tmp/.screenrc-XxY )
.TP
.B -o OPTION CHAIN
Add lines to the screen configuration file. OPTION CHAIN is a chain in the format "OPTION_1;...;OPTION_N". 
.T
.B -t
Print the newly generated screen configuration file on terminal and prevent screen from running.
.TP
.B -h, --help
Display help
.TP
.B -v
Activate debug mode. 

.SH EXAMPLES


1) 
.B screen-generator -c "watch ls /tmp;lsblk;tcpdump"   
Open a new screen composed of a grid of 2 lines and 2 colums

2)
.B screen-generator -c 'transmission-cli /root/+.torrent'
Launch a screen with as much windows as the number of file matching the pattern /root/*.torrent, + asks for an expansion of the command.

3) 
.B screen-generator -n -x 5 -y 3 -d $HOME/.screenrc
Replace the default configuration file of screen by a newly generated one decribing a 5x3 grid with $SHELL as window command.

.SH FILES

.B /tmp/screenrc-XxY-COMMAND-CHAIN
Generated configuration file.

.SH VARIABLES

The following variables are defined in 
.B
.B /usr/bin/screen-generator  

.B DEFAULT_EDITOR  
define the editor so that the cursor can automatically move when it is contained in a command chain. Set to vim as default

.B DEFAULT_NUMBER_OF_COLUMNS 
Set to 2 inititally.

.B DEFAULT_NUMBER_OF_LINES
Set to 1 inititally.

.B DEFAULT_SHORTCUTS 
Shortcuts can be changed by modifying this varialbe. They are initiated at:

.B "Ctrl+j"
Move to bottom window
.B "Ctrl+k"
Move to above window
.B "Ctrl+l"
Move to the right window
.B "Ctrl+h"
Move to left window
.B "Ctrl+y"
quit screen
.B "Ctrl+s"
split horizontally
.B "Ctrl+v"
split vertically

.B DEFAULT_OPTIONS
Option to be inserted in the screen. Set to null initially.

.SH SEE ALSO  
.BR screen
(1)

.SH AUTHOR

Any question, suggestions or remark can be sent at `jean.yvan.tissot[at]gmail.com`. Bugs can be reported on `https://github.com/boddhissattva/screen-generator`.

.SH VERSION

screen-generator v0.3.7
